//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFoody.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageViewModel
    {
        public string ManageViewModelID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string photo { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public int postcode { get; set; }
        public string district { get; set; }
        public string user_type { get; set; }
        public string status { get; set; }
    }
}
