//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheFoody.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_foods = new HashSet<Order_foods>();
        }
    
        public int Order_id { get; set; }
        public Nullable<int> Rest_id { get; set; }
        public string Cus_email { get; set; }
        public Nullable<System.DateTime> Order_date { get; set; }
        public string Order_type { get; set; }
        public string Delivery_address { get; set; }
        public string Phone { get; set; }
        public string Landmarks { get; set; }
        public string Payment_status { get; set; }
        public string Order_status { get; set; }
        public Nullable<System.DateTime> Dispatched_date { get; set; }
        public Nullable<decimal> Total_price { get; set; }
        public string Deliver_Man { get; set; }
        public Nullable<System.TimeSpan> Delivery_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_foods> Order_foods { get; set; }
        public virtual Order Order1 { get; set; }
        public virtual Order Order2 { get; set; }
        public virtual User User { get; set; }
    }
}
